#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_ros_driver.jointstates_integrator_node import KohakuJointStatesIntegratorNode


try:
    this_node = KohakuJointStatesIntegratorNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
