#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_ros_driver.kohaku_ros_driver_node import KohakuROSDriverNode

try:
    this_node = KohakuROSDriverNode()
    rospy.on_shutdown(this_node.shutdown)
    this_node.run()
except rospy.ROSInterruptException:
    pass
