kohaku_arm:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_yaw
    - shoulder_pitch
    - elbow_pitch
    - wrist_yaw
    - wrist_pitch
    - hand_yaw
  gains:
    shoulder_yaw: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    shoulder_pitch: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    elbow_pitch: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    wrist_yaw: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1}
    wrist_pitch: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1}
    hand_yaw: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1}
  constraints:
    goal_time: 3.0
  state_publish_rate: 25

kohaku_hand:
  type: effort_controllers/JointTrajectoryController
  publish_rate: 250
  joints:
    - l_finger_joint
    - r_finger_joint
  action_monitor_rate: 10
  state_publish_rate:  100
  stall_velocity_threshold: 0.01
  goal_tolerance: 0.2
  stall_timeout: 0.3
  gains:
    r_finger_joint: {p: 1.0, d: 0.0, i: 0.01, i_clamp: 1}
    l_finger_joint: {p: 1.0, d: 0.0, i: 0.01, i_clamp: 1}

gazebo_ros_control:
  pid_gains:
    shoulder_yaw: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    shoulder_pitch: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    elbow_pitch: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    wrist_yaw: {p: 1000.0, i: 0.01, d: 10.0, i_clamp: 1}
    wrist_pitch: {p: 100.0, i: 0.0, d: 0.01, i_clamp: 1}
    hand_yaw: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1}
    r_finger_joint: {p: 1000.0, i: 10.0, d: 0.01, i_clamp: 1}
    l_finger_joint: {p: 1000.0, i: 10.0, d: 0.01, i_clamp: 1}
