#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_simple_joint_command_sender.kohaku_simple_joint_command_sender_node import KohakuSimpleJointCommandSenderNode

try:
    this_node = KohakuSimpleJointCommandSenderNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
