controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_yaw
      - left_shoulder_pitch
      - left_elbow_pitch
      - left_wrist_yaw
      - left_wrist_pitch
      - left_hand_yaw
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_yaw
      - right_shoulder_pitch
      - right_elbow_pitch
      - right_wrist_yaw
      - right_wrist_pitch
      - right_hand_yaw
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_l_finger_joint
      - left_r_finger_joint
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - right_l_finger_joint
      - right_r_finger_joint
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []