# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: home_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_shoulder_yaw
    - left_shoulder_pitch
    - left_elbow_pitch
    - left_wrist_yaw
    - left_wrist_pitch
    - left_hand_yaw
    - left_l_finger_joint
    - left_r_finger_joint
    - right_shoulder_yaw
    - right_shoulder_pitch
    - right_elbow_pitch
    - right_wrist_yaw
    - right_wrist_pitch
    - right_hand_yaw
    - right_l_finger_joint
    - right_r_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: kohaku_leftarm
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_shoulder_yaw
      - left_shoulder_pitch
      - left_elbow_pitch
      - left_wrist_yaw
      - left_wrist_pitch
      - left_hand_yaw
  - name: kohaku_lefthand
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - left_l_finger_joint
      - left_r_finger_joint
  - name: kohaku_rightarm
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_shoulder_yaw
      - right_shoulder_pitch
      - right_elbow_pitch
      - right_wrist_yaw
      - right_wrist_pitch
      - right_hand_yaw
  - name: kohaku_righthand
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - right_l_finger_joint
      - right_r_finger_joint
